# Generated by Django 4.2 on 2023-05-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itineraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='itineraries/images')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('transport', models.CharField(max_length=100)),
                ('accommodation', models.CharField(max_length=100)),
                ('departureFrom', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_to_visit', models.CharField(choices=[('BEST', 'Best'), ('GOOD', 'Good'), ('MIXED', 'Mixed')], max_length=6)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='itineraries.itineraries')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.month')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraries')),
            ],
        ),
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraries')),
            ],
        ),
        migrations.CreateModel(
            name='Excluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraries.itineraries')),
            ],
        ),
        migrations.CreateModel(
            name='dayByDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='itineraries/daybyday')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daybyday', to='itineraries.itineraries')),
            ],
        ),
    ]
