# Generated by Django 4.2.2 on 2023-07-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glance',
            name='image',
        ),
    ]
