# Generated by Django 4.2 on 2023-05-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_glance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertview',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertview', to='accommodation.accommodation'),
        ),
    ]
