# Generated by Django 4.2.2 on 2023-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_glance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertip',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
