# Generated by Django 4.2 on 2023-05-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_alter_expertview_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glance',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance', to='accommodation.accommodation'),
        ),
        migrations.AlterField(
            model_name='insidertip',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insidertip', to='accommodation.accommodation'),
        ),
    ]
