# Generated by Django 4.2.2 on 2023-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_alter_insidertip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='luxury',
            field=models.BooleanField(default=False),
        ),
    ]
