# Generated by Django 4.2.2 on 2023-07-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_accommodation_luxury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='luxury',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='expertview',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
