# Generated by Django 4.2.2 on 2023-07-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_alter_accommodation_luxury_alter_expertview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertview',
            name='name',
            field=models.TextField(),
        ),
    ]
