# Generated by Django 4.2.2 on 2023-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_alter_expertview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertview',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='insidertip',
            name='description',
            field=models.TextField(),
        ),
    ]
