# Generated by Django 4.2.2 on 2023-07-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_alter_expertview_name_alter_insidertip_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidertip',
            name='accommodation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insidertip', to='accommodation.accommodation'),
        ),
    ]
