# Generated by Django 4.2 on 2023-05-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='destinations/image')),
                ('description', models.TextField()),
                ('homeof', models.CharField(blank=True, max_length=100, null=True)),
                ('famousfor', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_map', models.ImageField(blank=True, null=True, upload_to='destinations/map')),
                ('activities', models.ManyToManyField(to='shared.activity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='shared.country')),
                ('wildlife', models.ManyToManyField(to='shared.wildlife')),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_title', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='destination.destination')),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='DestinationMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_to_visit', models.CharField(choices=[('BEST', 'Best'), ('GOOD', 'Good'), ('MIXED', 'Mixed')], max_length=6)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='destination.destination')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.month')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='destination.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationAnimalsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mammal_species', models.CharField(max_length=50)),
                ('identified_bird_species', models.CharField(max_length=50)),
                ('amphibian_species', models.CharField(max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalsoverview', to='destination.destination')),
            ],
        ),
    ]
