# Generated by Django 4.2 on 2023-05-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationanimalsoverview',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animalsoverview', to='destination.destination'),
        ),
        migrations.AlterField(
            model_name='destinationtransport',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='destination.destination'),
        ),
    ]
