# Generated by Django 4.2.2 on 2023-07-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('enquire', '0003_enquire_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='travel_destination',
            field=models.ManyToManyField(blank=True, null=True, related_name='yourtrip', to='shared.country'),
        ),
    ]
