# Generated by Django 4.2.2 on 2023-07-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('enquire', '0004_alter_enquire_travel_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='travel_destination',
            field=models.ManyToManyField(blank=True, related_name='yourtrip', to='shared.country'),
        ),
    ]
